#!/usr/bin/python 
'''
/*                                                                              
** 109titrage for 109titrage in /home/orset_a/Maths/109titrage
**                                                                              
** Made by aurelie orset                                                        
** Login   <orset_a@epitech.net>                                                
**                                                                              
** Started on  Mon Mar 30 17:02:40 2015 aurelie orset                           
Last update Sun Apr  5 20:57:02 2015 aurelie orset
*/
'''

import os
import sys
import re
import fileinput
import string
import numpy
import math
from pylab import *

def parsing():
    if len(sys.argv) != 1:
        print ("Aucun arguments necessaires pour lancer le programme")
    tab = []
    while sys.stdin.readline() != 'FIN':
        tab += sys.stdin.readline()
def fonction(tab):
    x = -2.0
    xtab = []
    k = 0.0
    ytab = []
    y = 0.0
    while (x <= 2.0000000):
        while(k <= kmax):
            y += cos(a ** k * pi*x) / (2 ** k)
            k = k + 1
        ytab.append(y)
        k = 0.0
        y = 0.0
        xtab.append(x)
        x += 0.0001
    
    plot(xtab ,ytab)
    xlim(-2, 2)
    
    show()

parsing()
