##
## Makefile for 102chiffrement in /home/orset_a/rendu/Projet/102chiffrement
## 
## Made by aurelie orset
## Login   <orset_a@epitech.net>
## 
## Started on  Sun Nov 30 23:05:50 2014 aurelie orset
## Last update Sun Nov 30 23:07:13 2014 aurelie orset
##

SRC= 	cryp.c\
	convertbase.c\
	decryp.c\
	102chiffrement.c

NAME= 102chiffrement

CC= cc -o

all: $(NAME)

$(NAME): 
	$(CC) $(NAME) $(SRC) -lmy -L. -lm

clean:
	rm -f $(NAME)

fclean: clean

re: fclean all
