##
## Makefile for 101pong in /home/orset_a/rendu/101pong
## 
## Made by aurelie orset
## Login   <orset_a@epitech.net>
## 
## Started on  Tue Nov 11 15:00:35 2014 aurelie orset
## Last update Tue Nov 11 15:13:34 2014 aurelie orset
##

SRC = 101pong.c\
      my_getnbr.c\
      my_putstr.c\
      my_putchar.c

NAME = 101pong

CC = cc -o

RM = rm -f

all:	comp

comp:
	$(CC) $(NAME) $(SRC) -lm

fclean:	
	$(RM) $(NAME)

re: comp fclean all

.Phony: re comp fclean all
